#!/usr/bin/env node
/**
 * run-demo.mjs — runs the agent team once and writes everything the frontend
 * needs.
 *
 *   node run-demo.mjs            run, write web/data/run.json + run.js
 *   node run-demo.mjs --print    also print a readable transcript
 *   node run-demo.mjs --pace 350 run with a delay between steps (live mode)
 *   node run-demo.mjs --check    run the self-tests and exit non-zero on failure
 *
 * Writing `run.js` (which assigns to window.TAXFIX_RUN) is what lets the demo be
 * opened straight from disk with no server and no CORS problems.
 */

import { mkdir, writeFile } from 'node:fs/promises';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { runTeam } from './agents/orchestrator.mjs';
import { selfTest } from './agents/self-test.mjs';

const here = dirname(fileURLToPath(import.meta.url));
const argv = process.argv.slice(2);
const has = (flag) => argv.includes(flag);
const valueOf = (flag, fallback) => {
  const i = argv.indexOf(flag);
  return i >= 0 && argv[i + 1] ? Number(argv[i + 1]) : fallback;
};

function transcript(run) {
  const lines = [];
  const bar = '─'.repeat(72);
  lines.push(bar);
  lines.push(`  TAXFIX LOOP — agent run ${run.meta.runId}`);
  lines.push(`  ${run.meta.agentCount} agents · ${run.meta.ragChunks} knowledge chunks · ${run.meta.durationMs}ms`);
  lines.push(bar);
  lines.push('');
  lines.push(`BRIEF  ${run.brief}`);
  lines.push('');
  for (const step of run.timeline) {
    const stamp = String((step.at / 1000).toFixed(2)).padStart(6);
    const status = step.status.toUpperCase().padEnd(9);
    lines.push(`  ${stamp}s  ${step.emoji} ${step.agentName.padEnd(20)} ${status} ${step.title}`);
    if (step.detail) lines.push(`  ${' '.repeat(10)}${' '.repeat(20)}           ${step.detail}`);
  }
  lines.push('');
  lines.push(bar);
  lines.push(`  Readiness      ${run.dashboard.readinessBefore}% (${run.dashboard.labelBefore}) → ${run.dashboard.readinessAfter}% (${run.dashboard.labelAfter})`);
  lines.push(`  Confidence     ${run.dashboard.confidenceBefore}/5 → ${run.dashboard.confidenceAfter}/5`);
  lines.push(`  Claims audited ${run.metrics.claimsAudited} · blocked ${run.metrics.claimsBlocked}`);
  lines.push(`  Unsafe copy    ${run.metrics.unsafeMessagesRejected} rejected · checklist ${run.metrics.checklistBefore}/7 → ${run.metrics.checklistAfter}/7`);
  lines.push(bar);
  return lines.join('\n');
}

async function main() {
  if (has('--check')) {
    const { failures, checks } = await selfTest(join(here, 'taxfix_loop_rag'));
    for (const c of checks) console.log(`${c.pass ? '  ok  ' : ' FAIL '} ${c.label}${c.pass ? '' : ` — ${c.detail}`}`);
    console.log(`\n${checks.length - failures} / ${checks.length} checks passed`);
    process.exit(failures > 0 ? 1 : 0);
  }

  const run = await runTeam({
    ragDir: join(here, 'taxfix_loop_rag'),
    pace: valueOf('--pace', 0),
  });

  const outDir = join(here, 'web', 'data');
  await mkdir(outDir, { recursive: true });
  await writeFile(join(outDir, 'run.json'), JSON.stringify(run, null, 2), 'utf8');
  await writeFile(
    join(outDir, 'run.js'),
    `/* generated by run-demo.mjs — do not edit by hand */\nwindow.TAXFIX_RUN = ${JSON.stringify(run, null, 2)};\n`,
    'utf8',
  );

  if (has('--print') || valueOf('--pace', 0) > 0) {
    console.log(transcript(run));
  } else {
    console.log(`✓ agent run complete — ${run.timeline.length} steps, ${run.meta.agentCount} agents`);
  }
  console.log(`  readiness ${run.dashboard.readinessBefore}% → ${run.dashboard.readinessAfter}%  ·  confidence ${run.dashboard.confidenceBefore}/5 → ${run.dashboard.confidenceAfter}/5`);
  console.log('  wrote web/data/run.json and web/data/run.js');
}

main().catch((err) => {
  console.error(err);
  process.exit(1);
});
